name: promote
on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch: {}

env:
  GO_VERSION: 1.18

jobs:
  release:
    name: promote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make promote
